nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - "php"
  volumes: 
    - /Users/weirufeng/Work/meizu/svn/i18n.meizu.com/:/opt/htdocs/i18n.meizu.com/

php:
  build: ./php
  ports: 
    - "9000:9000"
  links:
    - "mysql"
    - "redis"
  volumes:
    - /Users/weirufeng/Work/meizu/svn/i18n.meizu.com/:/opt/htdocs/i18n.meizu.com/

mysql:
  build: ./mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: meizu.com

redis:
  build: ./redis
  ports:
  - "6379:6379"