nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - "php"
  volumes: 
    - /path/to/your/project/:/opt/htdocs/project/

php:
  build: ./php
  links:
    - "mysql"
    - "redis"
  volumes:
    - /path/to/your/project/:/opt/htdocs/project/

mysql:
  build: ./mysql
  environment:
    MYSQL_ROOT_PASSWORD: your-mysql-password

redis:
  build: ./redis
  ports:
  - "6379:6379"