nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - "php"
  volumes: 
<<<<<<< HEAD
    - /Users/weirufeng/Work/meizu/svn/i18n.meizu.com/:/opt/htdocs/i18n.meizu.com/
=======
    - /path/to/your/project/:/opt/htdocs/project/
>>>>>>> 42ca02a9e143b29cc97b071eedd04c763d33e2ef

php:
  build: ./php
  links:
    - "mysql"
    - "redis"
  volumes:
<<<<<<< HEAD
    - /Users/weirufeng/Work/meizu/svn/i18n.meizu.com/:/opt/htdocs/i18n.meizu.com/
=======
    - /path/to/your/project/:/opt/htdocs/project/
>>>>>>> 42ca02a9e143b29cc97b071eedd04c763d33e2ef

mysql:
  build: ./mysql
  environment:
<<<<<<< HEAD
    MYSQL_ROOT_PASSWORD: meizu.com
=======
    MYSQL_ROOT_PASSWORD: your-mysql-password
>>>>>>> 42ca02a9e143b29cc97b071eedd04c763d33e2ef

redis:
  build: ./redis
  ports:
  - "6379:6379"