nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - "php"
  volumes: 
    - ./code/:/opt/htdocs/code/

php:
  build: ./php
  ports: 
    - "9000:9000"
  links:
    - "mysql"
    - "redis"
  volumes:
    - ./code/:/opt/htdocs/code/

mysql:
  build: ./mysql
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456

redis:
  build: ./redis
  ports:
  - "6379:6379"